anweiss/cddl

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, src/ast.rs, src/lexer.rs, src/parser.rs, src/token.rs, src/validation/json/mod.rs, www/package-lock.json, www/package.json
=> Fix group choice, group entry, occurrence operator and tag parsing issues

Cargo.toml, src/ast.rs, src/lexer.rs, src/parser.rs, src/validation/cbor.rs, src/validation/json/controls.rs, src/validation/json/mod.rs, src/validation/mod.rs, tests/cddl.rs, tests/data/mod.rs
=> Error handling improvements

Cargo.toml
=> Cargo publishing fix

.github/workflows/publish.yml, .npmrc
Fix registry URL in .npmrc and publish dir
=> Fix registry URL in .npmrc and publish dir

www/package-lock.json, www/package.json
=> Update minimist dep

.github/workflows/ci.yml, .github/workflows/release.yml, src/bin/cddl.rs, src/lexer.rs, src/parser.rs, src/validation/cbor.rs, src/validation/json/mod.rs, www/package-lock.json
Better WASM error handling and clippy fixes.
=> WASM and linting cleanup

tests/cbor_tests.rs, tests/cddl.rs, tests/data/mod.rs
There are a number of array validation failures that I'd like to work on but since I have a collection of tests that I *think* are correct I thought I'd send out for review.
There are a number of things that are disabled; all should have "FIXME" comments attached.  Feel free to point out any that seem incorrect.
=> Cbor tests

Cargo.toml
Remove unneeded regex features to address #17.
=> Remove unneeded regex features

src/parser.rs
=> Fix memberkey parsing with type choice idents in std prelude

.github/workflows/ci.yml, Cargo.toml, src/bin/cddl.rs, src/lexer.rs, src/parser.rs, src/repl.rs, src/token.rs, src/validation/cbor.rs, src/validation/json/mod.rs, tests/cddl.rs
Replace annotate-snippets with codespan-reporting crate
=> Replace annotate-snippets with codespan-reporting crate

.github/workflows/ci.yml, Cargo.toml, README.md, src/parser.rs, src/repl.rs
Cleanup any unneeded dependencies
=> Cleanup deps

Cargo.toml, src/lexer.rs, src/parser.rs
Remove erroneous allocations and clean up deps
=> Remove erroneous allocations

src/lexer.rs, src/parser.rs, www/package-lock.json, www/package.json
Update deps and address detected vulnerabilities
=> Update deps and address detected vulnerabilities

Cargo.toml, cddl-lsp/package-lock.json, cddl-lsp/package.json, www/package-lock.json, www/package.json, www/webpack.config.js, www/webpack.config.prod.js
Address latest dependency vulnerabilities
=> Address dependency vulnerabilities

cddl-lsp/server/package-lock.json, cddl-lsp/server/package.json, cddl-lsp/server/webpack.config.js
=> Fix remaining vulnerability

Dockerfile, README.md, src/bin/cli.rs, src/lib.rs
CLI support for CBOR and Dockerfile fixes
=> CLI support for CBOR and Dockerfile fixes

Cargo.toml, README.md, src/error.rs, src/lexer.rs, src/lib.rs
Support for hexfloat and exponent. Completes full lexing and parsing implementation of the spec
=> Support for hexfloat and exponent

README.md, src/bin/cli.rs, src/lib.rs
=> CLI fixes and cleanup

.github/workflows/ci.yml, src/parser.rs
=> Fix newline parsing bug

src/validator/cbor.rs, src/validator/json.rs
=> Map validation fixes

.github/workflows/ci.yml, Cargo.toml, README.md, cddl-lsp/client/package-lock.json, cddl-lsp/package-lock.json, cddl-lsp/server/package-lock.json, src/ast.rs, src/bin/cli.rs, src/lexer.rs, src/lib.rs, src/parser.rs, src/validator/cbor.rs, src/validator/json.rs, src/validator/mod.rs, src/visitor.rs, www/package-lock.json
Addresses known vulnerabilities in dependencies and updates existing dependencies. Also bumps the MSRV to 1.46.0.
=> Vulnerability fixes and dep updates

src/validator/cbor.rs, src/validator/json.rs
=> Fix type choice in array error collection logic

src/validator/cbor.rs, src/validator/json.rs
Fixes size control validation errors as reported in #126
=> Fix size control validation errors

Cargo.toml, src/ast.rs, src/bin/cli.rs, src/lexer.rs, src/parser.rs, src/token.rs, src/validator/cbor.rs, src/validator/json.rs, src/validator/mod.rs
=> Exact occurrence validation for object entries

src/ast.rs, src/validator/cbor.rs, src/validator/json.rs
=> Fix optional field validation bug

src/bin/cli.rs, src/parser.rs
Highlights root type name used for validation
=> Root type for validation

src/validator/cbor.rs
=> Fix CBOR validation regression

src/lexer.rs, www/package-lock.json
=> Fix int parsing error in wasm

src/parser.rs
=> Fix whitespace bug in arrowmap keys

src/parser.rs
=> Fix issue parsing type rule with parenthesized type and operator

src/validator/mod.rs
=> Cleanup cddl::validate

.github/workflows/ci.yml, Cargo.toml, Dockerfile, README.md, src/lib.rs, src/validator/cbor.rs, src/validator/control.rs
=> Fix abnfb control validation bug

src/validator/cbor.rs, src/validator/json.rs
Fixes in the bugs reported in #197.
=> Fix type choice array validation errors

src/validator/cbor.rs, src/validator/json.rs, src/validator/mod.rs
=> Fix CBOR tag validation in arrays

.github/workflows/ci.yml, .github/workflows/publish-website.yml, Cargo.toml, src/bin/cli.rs, tests/wasm.rs, www/package-lock.json
Fixes #205 and other wasm build errors. Also adds wasm integration tests.
=> Update CI and fix wasm build flags

.github/workflows/ci.yml, .github/workflows/compilation-check.yml, .github/workflows/lsp-extension.yml, .github/workflows/publish-website.yml, .github/workflows/publish.yml, .github/workflows/release-cddl.yml, Cargo.toml, README.md, cddl-lsp/package-lock.json, cddl-lsp/package.json, src/lexer.rs, src/lib.rs
Sec fixes and workflow updates
=> Sec fixes and workflow updates

src/validator/cbor.rs, src/validator/json.rs
Fix nested array validation issues in #218
=> Fix nested array validation issues

.github/workflows/anchore.yml, src/parser.rs
=> Fix parsing errors

.github/workflows/ci.yml, README.md, src/ast/mod.rs, src/error.rs, src/lexer.rs, src/lib.rs, src/parser.rs, src/token.rs, src/validator/cbor.rs
=> Implements rfc-9682
